import os

master_snakefile_prefix = os.path.dirname(os.path.dirname(workflow.snakefile))


# -------- Config files -------- #
configfile: master_snakefile_prefix + "/config/config.yaml"


if os.path.exists("config/config.yaml"):

    configfile: "config/config.yaml"


# --------- Load Rules --------- #
include: "rules/common.smk"
include: "rules/prepare.smk"
include: "rules/dss.smk"


# ----------- Target ----------- #
rule all:
    input:
        get_final_output,
